Repository OneSignalDevelopers/ngosi, pull requests merged in 2021-12, with the labels that each got.

#32 Adds a preso list page
  components/Footer.tsx
  pages/preso.tsx
  pages/presos.tsx
  pages/qr.tsx
Labels: feature

#35 Teach me how to go
  .env.example
  README.md
  db.sql
Labels: documentation

#27 Http status codes
  package.json
  pages/api/preso.ts
  pages/api/profile.ts
  pages/api/survey-response.ts
  pages/api/survey.ts
  yarn.lock
Labels: dependencies

#37 Add page to view all attendees
  db.sql
  pages/groupies.tsx
  pages/presos.tsx
  types.ts
Labels: feature
