Repository OneSignalDevelopers/ngosi, pull requests merged in 2022-01, with the labels that each got.

#44 Styled the QR code page
  pages/qr.tsx
Labels: ui

#49 Styled and centered the Account component and account page
  components/Account.tsx
  components/Auth.tsx
  package.json
  pages/account.tsx
  pages/index.tsx
  pages/signin.tsx
  tailwind.config.js
  yarn.lock
Labels: ui

#43 Styled login page
  components/Auth.tsx
  package.json
  pages/index.tsx
  pages/signin.tsx
  tailwind.config.js
  yarn.lock
Labels: ui

#45 Center auth component on login page
  components/Auth.tsx
Labels: ui

#47 Convert useSupabase hook to use the provider pattern
  common/supabaseProvider.tsx
  components/Account.tsx
  components/Auth.tsx
  pages/_app.tsx
  pages/account.tsx
  pages/api/auth.ts
  pages/api/common/supabase.ts
  pages/api/preso.ts
  pages/api/profile.ts
  pages/api/survey-response.ts
  pages/api/survey.ts
  pages/groupies.tsx
  pages/index.tsx
  pages/preso.tsx
  pages/presos.tsx
Labels: improvement

#59 Centering Preso Form on preso page
  components/PresoForm.tsx
  pages/preso.tsx
Labels: ui

#52 Add detail page for presos
  common/supabaseProvider.tsx
  components/Account.tsx
  components/Auth.tsx
  components/PresoDetails.tsx
  db.sql
  pages/account.tsx
  pages/groupies.tsx
  pages/index.tsx
  pages/preso/[presoShortCode].tsx
  pages/presos.tsx
  pages/response/[presoId].tsx
  types.ts
Labels: improvement

#62 Add initial migration for DB in Supabase
  supabase/migrations/20220126224248_initial-schema.sql
Labels: migration
